openapi: 3.0.1
info:
  title: Get Latest Thread from Zoho Desk Ticket
  description: Récupère le dernier message (thread) d'un ticket Zoho Desk
  version: v1
servers:
  - url: https://desk.zoho.eu
security:
  - OAuth2:
      - Desk.tickets.READ
paths:
  /api/v1/tickets/{ticket_id}/threads:
    get:
      summary: Get latest thread from a ticket
      operationId: getLatestThread
      parameters:
        - name: ticket_id
          in: path
          description: The unique ID of the ticket
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Number of threads to fetch (use 1 for latest)
          required: false
          schema:
            type: integer
            default: 1
        - name: sortBy
          in: query
          description: Sort by sendDateTime descending to get latest first
          required: false
          schema:
            type: string
            default: "-sendDateTime"
      responses:
        "200":
          description: Thread retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        content:
                          type: string
                        contentType:
                          type: string
                        direction:
                          type: string
                        fromEmailAddress:
                          type: string
                        to:
                          type: string
                        summary:
                          type: string
                        createdTime:
                          type: string
        "404":
          description: Ticket not found
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.zoho.eu/oauth/v2/auth
          tokenUrl: https://accounts.zoho.eu/oauth/v2/token
          scopes:
            Desk.tickets.READ: Permission to read Zoho Desk tickets
