openapi: 3.0.1
info:
  title: Get Related Deals from Contact in Zoho CRM
  description: Récupère les Deals (formations) associés à un contact dans Zoho CRM
  version: v1
servers:
  - url: https://www.zohoapis.eu/crm/v2
security:
  - OAuth2:
      - ZohoCRM.modules.deals.READ
paths:
  /Contacts/{contact_id}/Deals:
    get:
      summary: Get deals related to a contact
      operationId: getRelatedDeals
      parameters:
        - name: contact_id
          in: path
          description: The unique ID of the contact
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: Fields to return in the response
          required: false
          schema:
            type: string
            default: "id,Deal_Name,Stage,Amount,From_Date,To_Date,Closing_Date,Type_de_formation"
      responses:
        "200":
          description: Deals retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        Deal_Name:
                          type: string
                        Stage:
                          type: string
                        Amount:
                          type: number
                        From_Date:
                          type: string
                          format: date
                        To_Date:
                          type: string
                          format: date
                        Closing_Date:
                          type: string
                          format: date
                        Type_de_formation:
                          type: string
        "204":
          description: No deals found
        "401":
          description: Unauthorized
        "404":
          description: Contact not found
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.zoho.eu/oauth/v2/auth
          tokenUrl: https://accounts.zoho.eu/oauth/v2/token
          scopes:
            ZohoCRM.modules.deals.READ: Permission to read Zoho CRM deals
