openapi: 3.0.1
info:
  title: Send Email Reply to Zoho Desk Ticket
  description: Envoie une réponse par email à un ticket Zoho Desk
  version: v1
servers:
  - url: https://desk.zoho.eu
security:
  - OAuth2:
      - Desk.tickets.UPDATE
paths:
  /api/v1/tickets/{ticket_id}/sendReply:
    post:
      summary: Send an email reply to a ticket
      operationId: sendEmailReply
      parameters:
        - name: ticket_id
          in: path
          description: The unique ID of the ticket
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                channel:
                  type: string
                  description: Channel for the reply
                  example: EMAIL
                  default: EMAIL
                to:
                  type: string
                  description: Recipient email address
                  example: client@example.com
                fromEmailAddress:
                  type: string
                  description: Sender email address (must be configured in Zoho Desk)
                  example: contact@cab-formations.fr
                contentType:
                  type: string
                  description: Content type of the reply
                  enum:
                    - plainText
                    - html
                  default: html
                content:
                  type: string
                  description: HTML or plain text content of the email reply
                  example: "<p>Bonjour, merci pour votre message...</p>"
                isForward:
                  type: boolean
                  description: Whether this is a forward instead of a reply
                  default: false
      responses:
        "200":
          description: Reply sent successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Ticket Not Found
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.zoho.eu/oauth/v2/auth
          tokenUrl: https://accounts.zoho.eu/oauth/v2/token
          scopes:
            Desk.tickets.UPDATE: Permission to update Zoho Desk tickets
