openapi: 3.0.1
info:
  title: Update Contact in Zoho CRM
  description: Met à jour les informations d'un contact dans Zoho CRM
  version: v1
servers:
  - url: https://www.zohoapis.eu/crm/v2
security:
  - OAuth2:
      - ZohoCRM.modules.contacts.UPDATE
paths:
  /Contacts/{contact_id}:
    put:
      summary: Update a contact record
      operationId: updateContact
      parameters:
        - name: contact_id
          in: path
          description: The unique ID of the contact to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      Phone:
                        type: string
                        description: Phone number
                      Mobile:
                        type: string
                        description: Mobile phone number
                      Mailing_Street:
                        type: string
                        description: Street address
                      Mailing_City:
                        type: string
                        description: City
                      Mailing_Zip:
                        type: string
                        description: Postal code
                      Mailing_Country:
                        type: string
                        description: Country
                      Description:
                        type: string
                        description: Additional notes or description
      responses:
        "200":
          description: Contact updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        details:
                          type: object
                        message:
                          type: string
                        status:
                          type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Contact not found
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.zoho.eu/oauth/v2/auth
          tokenUrl: https://accounts.zoho.eu/oauth/v2/token
          scopes:
            ZohoCRM.modules.contacts.UPDATE: Permission to update Zoho CRM contacts
