openapi: 3.0.1
info:
  title: Update Deal in Zoho CRM
  description: Met à jour les informations d'un Deal (formation) dans Zoho CRM
  version: v1
servers:
  - url: https://www.zohoapis.eu/crm/v2
security:
  - OAuth2:
      - ZohoCRM.modules.deals.UPDATE
paths:
  /Deals/{deal_id}:
    put:
      summary: Update a deal record
      operationId: updateDeal
      parameters:
        - name: deal_id
          in: path
          description: The unique ID of the deal to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      Session_choisie:
                        type: string
                        description: Chosen session ID (e.g., "CDJ-31-03-2026")
                      Date_debut_session:
                        type: string
                        format: date
                        description: Session start date
                      Date_fin_session:
                        type: string
                        format: date
                        description: Session end date
                      Date_examen_VTC:
                        type: string
                        format: date
                        description: VTC exam date
                      Preference_horaire:
                        type: string
                        enum: [jour, soir]
                        description: Time preference (day or evening)
                      Evalbox:
                        type: string
                        description: ExamT3P status mapping
                      Description:
                        type: string
                        description: Additional notes
      responses:
        "200":
          description: Deal updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        details:
                          type: object
                        message:
                          type: string
                        status:
                          type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Deal not found
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.zoho.eu/oauth/v2/auth
          tokenUrl: https://accounts.zoho.eu/oauth/v2/token
          scopes:
            ZohoCRM.modules.deals.UPDATE: Permission to update Zoho CRM deals
